on:
  workflow_dispatch:
    inputs:
      username:
        description: 'A username passed from the caller workflow'
        default: 'john-doe'
        required: false
        type: string
    secrets:
      token:
        description: 'password'
        required: true
  
jobs:
  print-username:
    runs-on: ubuntu-latest

    steps:
      - name: Print the input name to STDOUT
        run: echo The username is ${{ github.event.inputs.username }}
      - name: Print the input name to STDOUT
        run: echo The username is ${{ github.event.secrets.token }}